In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1 - x)


In [4]:
class NeuralNetwork:
    def __init__(self, x, y, n_hidden):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], n_hidden)
        self.weights2 = np.random.rand(n_hidden, 1)
        self.y = y
        self.output = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [7]:
def solve_boolean_function(n, function):
    if function == 'AND':
        X = np.array([list(map(int, list(format(i, '0' + str(n) + 'b')))) for i in range(2**n)])
        y = np.array([all(x) for x in X]).reshape(-1, 1)
    elif function == 'OR':
        X = np.array([list(map(int, list(format(i, '0' + str(n) + 'b')))) for i in range(2**n)])
        y = np.array([any(x) for x in X]).reshape(-1, 1)
    elif function == 'XOR':
        X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
        y = np.array([[0], [1], [1], [0]])
    else:
        raise ValueError('Invalid function')

    nn = NeuralNetwork(X, y, n_hidden=5)

    for _ in range(2000):
        nn.feedforward()
        nn.backprop()

    return nn.output


[[2.95638942e-04]
 [1.31337965e-02]
 [1.27934079e-02]
 [9.80636267e-01]]
[[0.02188957]
 [0.98767646]
 [0.98775252]
 [0.99647636]]
[[0.03090091]
 [0.9748975 ]
 [0.97461113]
 [0.02354219]]


In [8]:
print(solve_boolean_function(2, 'AND'))
print(solve_boolean_function(2, 'OR'))
print(solve_boolean_function(2, 'XOR'))

[[3.94905492e-04]
 [1.34273881e-02]
 [1.72308397e-02]
 [9.76566843e-01]]
[[0.02047063]
 [0.98781147]
 [0.98849717]
 [0.99631125]]
[[0.03257629]
 [0.97306899]
 [0.97106798]
 [0.0243505 ]]
